language: cpp
compiler:
- clang
- gcc
os:
- linux
- osx

install:
  - sudo pip install cpp-coveralls
  
script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ./unit_tests

after_success:
  - coveralls --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*"
